services:
  ishtech-oms-mariadb:
    image: mariadb:latest
    container_name: ishtech_oms_mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: Qwer4321
      LANG: C.UTF-8
      TZ: ${TZ:-Europe/Helsinki}
    ports:
      - "${DB_PORT:-23306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/main/resources/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - ishtech-oms-network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 5m
      start_period: 30s

  ishtech-oms-springboot:
    build:
      context: .
      dockerfile: build.Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT:-8080}
        TZ: ${TZ:-Europe/Helsinki}
    container_name: ishtech_oms_springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://ishtech-oms-mariadb:3306/ishtech_oms_dev_db
      SPRING_FLYWAY_URL: jdbc:mariadb://ishtech-oms-mariadb:3306/ishtech_oms_dev_db
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      ishtech-oms-mariadb:
        condition: service_healthy
    networks:
      - ishtech-oms-network

networks:
  ishtech-oms-network:
    driver: bridge

volumes:
  mariadb_data:
